definitions:
  models.CreatePostModel:
    properties:
      author:
        type: string
      body:
        type: string
      title:
        type: string
    type: object
  models.GetAllPostsModel:
    properties:
      count:
        type: integer
      posts:
        items:
          $ref: '#/definitions/models.GetPostModel'
        type: array
    type: object
  models.GetPostModel:
    properties:
      author:
        type: string
      body:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  models.ResponseError:
    properties:
      error:
        type: object
    type: object
  models.ResponseOK:
    properties:
      message:
        type: object
    type: object
  models.UpdatePostModel:
    properties:
      author:
        type: string
      body:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/posts:
    get:
      consumes:
      - application/json
      description: API for getting posts
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllPostsModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      security:
      - ApiKeyAuth: []
      summary: Get All Posts
      tags:
      - post
  /v1/posts/:
    post:
      consumes:
      - application/json
      description: API for create post
      parameters:
      - description: Create Post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.CreatePostModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetPostModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Create Post
      tags:
      - post
  /v1/posts/{post_id}:
    delete:
      consumes:
      - application/json
      description: API for deleting post object
      parameters:
      - description: post_id
        in: path
        name: post_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseOK'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Delete Post
      tags:
      - post
    get:
      consumes:
      - application/json
      description: API for getting post info
      parameters:
      - description: post_id
        in: path
        name: post_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetPostModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Get Post
      tags:
      - post
    put:
      consumes:
      - application/json
      description: API for updating post
      parameters:
      - description: post_id
        in: path
        name: post_id
        required: true
        type: integer
      - description: post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.UpdatePostModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetPostModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Update Post
      tags:
      - post
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
